### ISSUE TITLE
Upgrade to latest freeze-dry - solves at least one parsing issue

### ISSUE THREAD

**Issue by motin** [erikrose/fathom-fox#7]
Tried saving https://css-tricks.com/snippets/css/a-guide-to-flexbox/ with fathom-fox and it ends up with a broken page. Seems to be related to freeze-dry 0.1.0 used in fathom-fox, since saving with https://github.com/WebMemex/webmemex-extension works and [it uses 0.1.2](https://github.com/WebMemex/webmemex-extension/blob/master/package.json#L29)

**Comment by erikrose** [comment]
Upgraded to 0.2.0 awhile ago.
