### ISSUE TITLE
Training UI stalls if any tab with a protected host is open

### ISSUE THREAD

**Issue by weaversam8** [erikrose/fathom-fox#9]
The extension requests permission to operate on any site, using the `<all_urls>` key in the extension manifest, but this doesn't grant permissions for the host `addons.mozilla.org`. If I recall correctly, this is due to security concerns and is part of the WebExtensions spec. 

Unfortunately, if in the training UI, clicking the "Train on the tabs in this window" button will cause no action to occur if any tab containing a host we don't have permissions for, such as `addons.mozilla.org`. This is a (relatively) silent failure, the only indication that something went wrong is the error message:

```
Error: Missing host permission for the tab
```

in the Javascript console. It might be possible to better document this failure in the UI.

**Comment by erikrose** [comment]
It is true! I always tap-dance around it, but it would be great to solve properly.

**Comment by erikrose** [comment]
In-browser training is deprecated as of Fathom 3.
